auto: true
url: https://github.com/vardhaman22/cis-operator.git
chartRepoBranch: rke2-cis-1.9
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/vardhaman22/cis-operator.git
      chartRepoBranch: rke2-cis-1.9
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true