auto: true
url: https://github.com/vardhaman22/cis-operator.git
chartRepoBranch: test-eks
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/vardhaman22/cis-operator.git
      chartRepoBranch: test-eks
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true