auto: true
url: https://github.com/vardhaman22/cis-operator.git
chartRepoBranch: v1.4/custom-volume-mount
subdirectory: chart
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/vardhaman22/cis-operator.git
      chartRepoBranch: v1.4/custom-volume-mount
      subdirectory: crds
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true