{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sachet.fullname" . }}
  namespace: {{ include "sachet.namespace" . }}
  labels: {{ include "sachet.labels" . | nindent 4 }}
{{- end }}
