{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prom2teams.fullname" . }}
  namespace: {{ include "prom2teams.namespace" . }}
  labels: {{ include "prom2teams.labels" . | nindent 4 }}
{{- end }}
